{% set version = "3.0.1" %}

package:
  name: fusepy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fusepy/fusepy-{{ version }}.tar.gz
  sha256: 72ff783ec2f43de3ab394e3f7457605bf04c8cf288a2f4068b4cde141d4ee6bd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fuse

about:
  home: http://github.com/terencehonles/fusepy
  license: ISC
  # Waiting on https://github.com/fusepy/fusepy/pull/74
  # license_file: ''
  summary: Simple ctypes bindings for FUSE

extra:
  recipe-maintainers:
    - ocefpaf
