travis:
  secure:
    BINSTAR_TOKEN: dEfdYGigkHBy7S/gBCfTO73RCXbc+0eJ3sbrgrsazonuPW0mOGnQxm8rvmE72wL1Njh1AEC67bBmCe2ZZUXpxfElKmL6pteBn6wN1Dy+VL6bqu4JKk7CBT2ybSDmzsq8Ec5GrQq3djFgFJQrfLYoKXoa39zsfGR9RbvsI1j33PhrLrHrqwGdc97V6bBph3lLbmJj+Y/7EM3M66DAsbYoz9nKEChWWsJ3sNj+cqhmE4ahyw1nlh0E9zgQJ9Onx41bdoc1fvBRcZtZ1B6203EPODqwyiB6KJ4sSfh3YWb9+my31qAt+VlQuKpEosGdJnER8h5cSGUF7/F7ea+gg8aFk6BxoUqqpP4DtJnPwEIOwFjyX9gMDoe8oz+pIHJRWjNHaag4puNg9niy5MwwtSnAZjETOksnGqt00qgBFtxjE7lcO0aWMKzV36AKgaVccixwoZr6epYivImoCYkEWVE1nkQWD6Vxk25CPe356+s6wXE3CspDpMy4gbVt+UmFmXZHkbaDGW05Scro7jBu+mj0Dg1hWpkDJY4/qX+iV3mhQhL8irvGVu60XFE9ytNcWX+/jppyvV+QdurmFfgk4oc6zkHB85sGxwtU/UCedj0lBF2Mb+3Sla334eOhMJ8mlGsgp91O1OrRcIhPTqJLQQPdbto5Vq3EyToEuNplm74GZhg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
