travis:
  secure:
    BINSTAR_TOKEN: S+XXvhpgYe75M0ln5iJEavS1rLtdG9DYHeq08ufXWXoQklsGshiBjmOwegavcFYyefkOKxUWQAbQgVX66SpPBogRjWZudgreu4ULLRmRjYGQwGHuIJaJ2YZdyOgsELxj38Pbnyf7donWd45LZOz6LT8hP3so8/21meUga0dCfDzyPXtMmSd6gVQqeAiBzi+ijnktgLqQnN+TFTF/OakYp/lAivyp3sWi6Ej7tJxoG8WzNJ8a9emo0kDBLlcq09IlJd+Mpw0k6A3lSjHC539hBt9vJLGqae/UjeZ9F7o2XezGL3AEGPExLGqqjCAO4+dYXBl3GRu/azztHTteWGVmwk/yuS747IJIUtm4xu711QrUREJCaMgek9tx3+W+oGrY+ERCMjzFGZl0dLOZ0Y6ODsg08oyRlS/IL4kmFCRv7HyeUn01lD+hcCcnurVT0Gzfre6PQIHYn9TTeA7gYF0ZlIU3B1U33ft1MobDUuwQkTey3/LQ6zyZV55/KiMLyantxGUp6n4pwgo8SpaWddfTrOrSMmxN9q/0TiXEWIXmfJADDAWnxx3wzfoNWsJBSqS/QIailkfCkjQI+HKzO0sOnUWm0IYWXj2a0GWqCN0QZqyVhjO3zyApi0ryNJUq1q7eCM1/YaD2Da446bRm3nUCek9AGpXaPOgaeO0X7tXi6wg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
